name = "daimond113/lexi_cli"
version = "0.1.0"
description = "Localisation for Vide, simplified."
authors = ["daimond113 <contact@daimond113.com> (https://www.daimond113.com)"]
repository = "https://github.com/daimond113/lexi"
license = "MIT"

includes = ["src/**/*", "README.md"]

[target]
environment = "lune"
bin = "src/init.luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[engines]
lune = "^0.10.2"
