name: Build Release Executables

on:
    release

permissions:
    contents: write

env:
  GH_TOKEN: ${{ github.token }}

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v5
            - name: Setup Rokit
              uses: CompeyDev/setup-rokit@v0.1.2
            - name: Setup pesde
              uses: axiom-co/setup-pesde@b690699ace34169731b6b2a1c93b2008472038a7
              with:
                token: ${{ secrets.PESDE_TOKEN }}
                cache: true
            - name: Install Pesde Packages
              run:
                pesde install
            - name: Bundle
              run:
                pesde x pesde/darklua -- process pkgs/bin/src bundle
            - name: Lune Build
              run:
                lune build bundle/init.luau -o lexi-windows-x86_64 -t windows-x86_64;
                lune build bundle/init.luau -o lexi-windows-aarch64 -t windows-aarch64;
                lune build bundle/init.luau -o lexi-macos-x86_64 -t windows-x86_64;
                lune build bundle/init.luau -o lexi-macos-aarch64 -t windows-aarch64;
                lune build bundle/init.luau -o lexi-linux-x86_64 -t linux-x86_64;
                lune build bundle/init.luau -o lexi-linux-aarch64 -t linux-aarch64
            - name: Release files
              run:
                gh release upload ${{github.event.release.tag_name}} lexi-windows-x86_64.exe;
                gh release upload ${{github.event.release.tag_name}} lexi-windows-aarch64.exe;
                gh release upload ${{github.event.release.tag_name}} lexi-macos-x86_64.exe;
                gh release upload ${{github.event.release.tag_name}} lexi-macos-aarch64.exe;
                gh release upload ${{github.event.release.tag_name}} lexi-linux-x86_64;
                gh release upload ${{github.event.release.tag_name}} lexi-linux-aarch64
